# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/arnold

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/arnold

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/arnold/CMakeFiles /home/david/arnold//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/arnold/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arnold

# Build rule for target.
arnold: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arnold
.PHONY : arnold

# fast build rule for target.
arnold/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/build
.PHONY : arnold/fast

Entities/Enemy.o: Entities/Enemy.cpp.o
.PHONY : Entities/Enemy.o

# target to build an object file
Entities/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Enemy.cpp.o
.PHONY : Entities/Enemy.cpp.o

Entities/Enemy.i: Entities/Enemy.cpp.i
.PHONY : Entities/Enemy.i

# target to preprocess a source file
Entities/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Enemy.cpp.i
.PHONY : Entities/Enemy.cpp.i

Entities/Enemy.s: Entities/Enemy.cpp.s
.PHONY : Entities/Enemy.s

# target to generate assembly for a file
Entities/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Enemy.cpp.s
.PHONY : Entities/Enemy.cpp.s

Entities/Player.o: Entities/Player.cpp.o
.PHONY : Entities/Player.o

# target to build an object file
Entities/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Player.cpp.o
.PHONY : Entities/Player.cpp.o

Entities/Player.i: Entities/Player.cpp.i
.PHONY : Entities/Player.i

# target to preprocess a source file
Entities/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Player.cpp.i
.PHONY : Entities/Player.cpp.i

Entities/Player.s: Entities/Player.cpp.s
.PHONY : Entities/Player.s

# target to generate assembly for a file
Entities/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Player.cpp.s
.PHONY : Entities/Player.cpp.s

Entities/Projectile.o: Entities/Projectile.cpp.o
.PHONY : Entities/Projectile.o

# target to build an object file
Entities/Projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Projectile.cpp.o
.PHONY : Entities/Projectile.cpp.o

Entities/Projectile.i: Entities/Projectile.cpp.i
.PHONY : Entities/Projectile.i

# target to preprocess a source file
Entities/Projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Projectile.cpp.i
.PHONY : Entities/Projectile.cpp.i

Entities/Projectile.s: Entities/Projectile.cpp.s
.PHONY : Entities/Projectile.s

# target to generate assembly for a file
Entities/Projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Entities/Projectile.cpp.s
.PHONY : Entities/Projectile.cpp.s

Game.o: Game.cpp.o
.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i
.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s
.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/Game.cpp.s
.PHONY : Game.cpp.s

MessageHandler.o: MessageHandler.cpp.o
.PHONY : MessageHandler.o

# target to build an object file
MessageHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/MessageHandler.cpp.o
.PHONY : MessageHandler.cpp.o

MessageHandler.i: MessageHandler.cpp.i
.PHONY : MessageHandler.i

# target to preprocess a source file
MessageHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/MessageHandler.cpp.i
.PHONY : MessageHandler.cpp.i

MessageHandler.s: MessageHandler.cpp.s
.PHONY : MessageHandler.s

# target to generate assembly for a file
MessageHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/MessageHandler.cpp.s
.PHONY : MessageHandler.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/arnold.dir/build.make CMakeFiles/arnold.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... arnold"
	@echo "... Entities/Enemy.o"
	@echo "... Entities/Enemy.i"
	@echo "... Entities/Enemy.s"
	@echo "... Entities/Player.o"
	@echo "... Entities/Player.i"
	@echo "... Entities/Player.s"
	@echo "... Entities/Projectile.o"
	@echo "... Entities/Projectile.i"
	@echo "... Entities/Projectile.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... MessageHandler.o"
	@echo "... MessageHandler.i"
	@echo "... MessageHandler.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

